### ISSUE TITLE
Withdraw all

### ISSUE THREAD

**Issue by peoplma** [BlockIo/block_io-python#11]
I've been having trouble trying to get a balance from a label address and withdraw all of it.  An error is raised saying that I don't have enough when I try to withdraw the whole balance - obviously - due to network fees.  But using the `block_io.get_network_fee_estimate` method returns the wrong fee amount for bitcoin, so I can't subtract that from the address balance either.  Is there a better way to withdraw the maximum amount from an address?

**Comment by v6** [comment]
// , These sort of fractional transactions kind of get killed by calculations for fees and other things.

**Comment by doersf** [comment]
Fee estimation has gotten alot simpler since this issue was opened. Here's how you get the max withdrawable balance now: 

1) You can just use the max available balance to get a network fee estimate. 
2) Then make another call with amount_used minus estimated fee returned. 
3) You should be able to request the withdrawal with the amount in (2).
